name: Ubuntu Build

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '30 0 * * 0'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Archer C6U v1
        run: chmod +x ./build_c6u.sh && ./build_c6u.sh
      - name: Build Archer C50 v6
        run: chmod +x ./build_c50.sh && ./build_c50.sh
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d_%H.%M.%S')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            images/*.bin
            images/*.version
            images/*.sha256
          body: Snapshot build at ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
