name: Ubuntu Build New

on:
  workflow_dispatch:
  push:
    paths:
      - 'build_requests.log'

env:
  C6Uv1: mt7621-tplink_archer-c6u-v1
  C50v6: mt76x8-tplink_archer-c50-v4

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            device: [ ArcherC6Uv1, ArcherC50v6 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build ${{ matrix.device }}
        run: chmod +x build_common.sh && cd ${{ matrix.device }} && ../build_common.sh
      - name: Upload firmware artifcats
        uses: actions/upload-artifact@master
        with:
          name: firmware_${{ matrix.device }}
          path: images/
          retention-days: 1

  post_build:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download ArcherC6Uv1 files
        uses: actions/download-artifact@master
        with:
          name: firmware_ArcherC6Uv1
          path: images/
      - name: Download ArcherC50v6 files
        uses: actions/download-artifact@master
        with:
          name: firmware_ArcherC50v6
          path: images/
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d_%H.%M.%S')"
      - name: Get firmware versions
        id: versions
        run: echo "::set-output name=c6u_ver::$(cat images/openwrt-ramips-$C6Uv1-squashfs-sysupgrade.version)" && echo "::set-output name=c50_ver::$(cat images/openwrt-ramips-$C50v6-squashfs-sysupgrade.version)"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            images/*.bin
            images/*.version
            images/*.sha256
          body: "Versions => Archer C6Uv1: ${{ steps.versions.outputs.c6u_ver }}, Archer C50v6: ${{ steps.versions.outputs.c50_ver }}"
          tag_name: ${{ steps.date.outputs.date }}
