name: Ubuntu Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: chmod +x ./build.sh && ./build.sh
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d_%H.%M.%S')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            openwrt-*/bin/targets/ramips/mt7621/*.bin
          body: Snapshot build at ${{ steps.date.outputs.date }}
          tag_name: ${{ steps.date.outputs.date }}
